variables:
  BUILD_TAG: ${CI_COMMIT_BRANCH}-build-${CI_PIPELINE_ID}

  ############################ CI PRODUCTION
  DOCKER_REGISTRY_DEVELOP: 611717736928.dkr.ecr.ap-southeast-1.amazonaws.com
  REPO_DEVELOP: ecr-uplive-intranet-frontend

  # ############################ CD PRODUCTION
  # CI_AWS_ECS_SERVICE_DEVELOP: ecs-svc-mep-caplize-frontend-prod
  # CI_AWS_ECS_TASK_DEFINITION_DEVELOP: td-mep-caplize-frontend-prod
  # AWS_DEFAULT_REGION_DEVELOP: ap-southeast-1
  # CI_AWS_ECS_CLUSTER_DEVELOP: ecs-mepcalize-prod

include:
  - project: 'mep/ci-template'
    ref: main
    file: 'cicd_ecr_ecs.yml'
