variables:
  BUILD_TAG: ${CI_COMMIT_BRANCH}-build-${CI_PIPELINE_ID}

  ############################ CI DEVELOP
  DOCKER_REGISTRY_DEVELOP: 611717736928.dkr.ecr.ap-southeast-1.amazonaws.com
  REPO_DEVELOP: ecr-upliveintranet-frontend

  ############################ CD DEVELOP
  CI_AWS_ECS_SERVICE_DEVELOP: ecs-svc-upliveintranet-frontend-prod
  CI_AWS_ECS_TASK_DEFINITION_DEVELOP: td-upliveintranet-frontend-prod
  AWS_DEFAULT_REGION_DEVELOP: ap-southeast-1
  CI_AWS_ECS_CLUSTER_DEVELOP: ecs-upliveintranet-prod

include:
  - project: 'mep/ci-template'
    ref: main
    file: 'cicd_ecr_ecs.yml'
